import fs from 'fs';
import path from 'path';

// 1. Read the CatalogTab.tsx file
// Use forward slashes to be safe or explicit backslashes
const catalogPath = path.join('c:/Users/TEC FAG/Pictures/Tecfag I.a (1.0.0)/Tecfag-I.A-1.0.0-/src/components/catalog/CatalogTab.tsx');
let catalogContent = '';
try {
    catalogContent = fs.readFileSync(catalogPath, 'utf-8');
    console.log(`Successfully read catalog file, length: ${catalogContent.length}`);
} catch (error) {
    console.error(`Error reading catalog file: ${error}`);
    process.exit(1);
}

// 2. User's List
const userListRaw = `
Abastecedor Automático (1)
QE-A - UNIDADE RESFRIADORA/REFRIGERADORA PARA AGUA GELADA
Alimentadores de Rosca (2)
ALIMENTADOR DE ROSCA PARA POS ALT. 2,5METROS - FUNIL 110 LITROS
ALIMENTADOR DE ROSCA PARA POS - FUNIL 110 LITROS
Aplicadores de Filme Stretch (4)
BL2000A - STRECHADEIRA AUTOMATICA DE PALETES
BL2000B - STRECHADEIRA AUTOMATICA DE PALETES
BL2000P - STRECHADEIRA AUTOMATICA DE PALETES
E610 - APLICADOR MANUAL DE FILME STRETCH
Arqueadoras (5)
AP301A - MAQUINA ARQUEADORA AUTOMATICA
MH301A - MAQUINA ARQUEADORA AUTOMATICA
SM10H - MAQ. SEMI-AUTOM. DE ARQUEAR 220V
XQD-19E - ARQUEADORA PNEUMATICA MANUAL
XQD-25E - ARQUEADORA PNEUMATICA MANUAL
Datadoras e Impressoras (8)
HP241C - DATADORA HOT STAMP ELETRICA
HP351 - DATADORA HOT STAMP MANUAL (diversas configurações)
M6 - IMPRESSORA MANUAL JATO DE TINTA
M7 - IMPRESSORA MANUAL JATO DE TINTA
MX1 - IMPRESSORA JATO DE TINTA
MX2 - IMPRESSORA JATO DE TINTA
MY380 - DATADOR COM TINTA SOLIDA E CONTADOR
MY380/M - DATADOR C/ BASE AUMENTADA
Dispensadores de Fita (3)
FX-800 - APLICADOR/DISPENSADOR SEMI AUTOMATICO P/ FITA GOMADA
FX-800C - DISPENSADOR AUTOMATICO DE FITA GOMADA
FX-800P - DISPENSADOR AUTOMATICO DE FITA GOMADA
Dosadoras (19)
DM1000F - DOSADORA C/ BALANCA P/ PÓS
DM1000S - DOSADORA C/ BALANCA P/ GRANULADOS
DM5000F - DOSADORA C/ BALANCA P/ PÓS
DM5000S - DOSADORA C/ BALANCA P/ GRANULADOS
KFG250 - MAQUINA SEMI-AUT. P/ ENCHIMENTO DE GRÃOS E FARELOS
KFG500 - MAQUINA SEMI-AUT. P/ ENCHIMENTO DE GRÃOS E FARELOS
KFG1000 - MAQUINA SEMI-AUT. P/ ENCHIMENTO DE GRÃOS E FARELOS
TDM25F - DOSADORA DE BANCADA P/ PÓS BAIXA FLUIDEZ
TDM25G - DOSADORA DE BANCADA P/ GRÃOS
TDM25P - DOSADORA DE BANCADA P/ PÓS
TDM25S - DOSADORA DE BANCADA P/ GRANULADOS
TDM100F - DOSADORA DE BANCADA P/ PÓS BAIXA FLUIDEZ
TDM100G - DOSADORA DE BANCADA P/ GRÃOS
TDM100P - DOSADORA DE BANCADA P/ PÓS
TDM100S - DOSADORA DE BANCADA P/ GRANULADOS
TDM200G - DOSADORA DE BANCADA P/ GRÃOS
TDM200P - DOSADORA DE BANCADA P/ PÓS
TDM500F - DOSADORA DE BANCADA P/ PÓS BAIXA FLUIDEZ
TDM500S - DOSADORA DE BANCADA P/ GRANULADOS
Empacotadoras Automáticas (16)
AFPP1328 - EMPACOTADORA P/ PÓS ALIM. HORIZONTAL
AFPP1328/P - EMPACOTADORA P/ PÓS C/ DOSAGEM PENDULAR
AFPP1528A - EMPACOTADORA 4 SOLDAS P/ PÓS
AFPP2030B - EMPACOTADORA P/ PÓS
AFPP2830B - EMPACOTADORA P/ SACHÊ TIPO STICK
AFPP320B - EMPACOTADORA C/ BALANÇA LINEAR 4 CABEÇAS
AFPP320C - EMPACOTADORA VERTICAL 10 CABEÇAS C/ BAL. ELETRÔNICA
AFPP420E - EMPACOTADORA DE ALTO DESEMPENHO P/ PÓS
AFPP420F - EMPACOTADORA DE ALTO DESEMPENHO
DIAMOND 180A - EMPACOTADORA POUCH
DXDZ-250B - FLOW PACK CONVENCIONAL
DXDZ-250X - FLOW PACK INVERTIDA
DZB1100C - EMBALADORA FLOW PACK HORIZONTAL
EXACTA 1328V - EMPACOTADORA VERTICAL DE SACHÊS
SW180A - EMPACOTADORA P/ SACOS PRÉ-FORMADOS/STAND UP POUCH
SW200/SW250/SW320 - EMPACOTADORA STAND UP POUCH P/ PÓS
Encapsuladoras (8)
FUSION 400 / 800 / 1200 / 2500 / 3500 - ENCAPSULADORA AUTOMÁTICA
UNION - ENCAPSULADORA SEMI-AUTOM. PAINEL ANALÓGICO
UNION PLUS - ENCAPSULADORA SEMI-AUTOM. C/ CLP
UNION PLUS/II - ENCAPSULADORA SEMI-AUTOM. C/ CLP
Encartuchadeiras (1)
ZH-50 - ENCARTUCHADEIRA ROTATIVA VERTICAL
Envasadoras (69)
A2 - ENVASADORA PNEUMÁTICA SEMI AUTOMÁTICA
A3 - ENVASADORA POR PRESSÃO MANUAL 50ML
A3D - ENVASADORA POR PRESSÃO MANUAL 50ML/100ML
A3E - ENVASADORA POR PRESSÃO MANUAL 100ML
AFPP220A - ENVASADORA DE LÍQ./PAST. EM EMBALAGENS ESPECIAIS
ALF500-2B / ALF500-4B - ENVASADORA AUTOM. P/ LÍQ.
ALF1000-2B / ALF1000-4B - ENVASADORA AUTOM. P/ LÍQ.
APF100-2B - ENVASADORA AUTOM. P/ LÍQ./PAST.
APF300-2B / APF300-4B - ENVASADORA AUTOM. P/ LÍQ./PAST.
APF500-2B / APF500-4B - ENVASADORA AUTOM. P/ LÍQ./PAST.
APF500-2B/B - ENVASADORA DE BANCADA P/ PASTOSOS
APF1000-2B / APF1000-4B / APF1000-6B - ENVASADORA AUTOM. P/ LÍQ./PAST.
APF2500-2B / APF2500-4B - ENVASADORA AUTOM. P/ LÍQ./PAST.
APF5000-2B / APF5000-4B - ENVASADORA AUTOM. P/ LÍQ./PAST.
APF10000 - ENVASADORA DE BANCADA C/ BOMBA DE ROTOR
DGF 100 / 300 / 500 / 1000 / 2500 / 5000 - ENVASADORA SEMI-AUTOM. P/ LÍQ. E PAST.
DGF 300/M - ENVASADORA SEMI-AUTOM. C/ BICO MÓVEL
DGF/H 300 / DGF/H 1000 / DGF/H 2500 - ENVASADORA SEMI-AUTOM. C/ MIXER
DGF2 100 / 300 / 500 / 1000 / 2500 / 5000 - ENVASADORA SEMI-AUTOM. 2 BICOS
DXDG-100II - ENVASADORA VOLUMÉTRICA AUTOMÁTICA
FRG2001E/4 - ENVASADORA E SELADORA AUTOMÁTICA DE COPOS
GENIUS 2 / GENIUS 2A - CONTADORA SEMI-AUTOMÁTICA DE CÁPSULAS
GENIUS 8 / GENIUS 12 / GENIUS 16 - CONTADORA ELETRÔNICA DE CÁPSULAS
HZK160 - ENVASADORA PERISTÁLTICA P/ LÍQUIDOS
LRDB1A - ENVASADORA PERISTÁLTICA P/ PASTOSOS/ESMALTE
SYF 100 / 300 / 500 / 1000 / 2500 / 5000 - ENVASADORA SEMI-AUT. P/ LÍQUIDOS
SYF2 100 / 300 / 500 / 1000 / 2500 - ENVASADORA SEMI-AUT. P/ LÍQUIDOS 2 BICOS
TLF600 / TLF600II - ENVASADORA DE 4 BICOS AUTOMÁTICA DE BANCADA
VSF - ENVASADORA SEMI AUTOMÁTICA PARA PÓS
VSF-30A - ENVASADORA AUTOM. P/ PÓS C/ ESTEIRA
VSF-30AGII / VSF-30AGIII - ENVASADORA AUTOM. P/ PÓS
VSF-30S / VSF 30S/B - ENVASADORA SEMIAUTOMÁTICA P/ PÓS
VSF-FZ3B - ENVASADORA AUTOMÁTICA ALTA PERFORMANCE P/ PÓS
VSFII-30A - ENVASADORA AUTOM. 2 BICOS P/ PÓS
VSF2000 - ENVASADORA P/ GRÃOS COM 4 BALANÇAS
ZPP40A - MÁQUINA ENVASADORA AUTOM. P/ COMP. EM TUBETES
Esteiras e Alimentadores (21)
ALIMENTADOR ELEVADOR DE CANECAS P/ EMPACOTADORAS
BC1.5M/200S - ESTEIRA FIXA LONA AÇO INOX
BC1M/W300P - ESTEIRA LONA 1M X 30CM
BC2.5M/300S - ESTEIRA INOX LONA 2,5M X 30CM
BC2.5M/W300P - ESTEIRA LONA 2,5M X 30CM
BC2.5M/W500P - ESTEIRA LONA 2,5M X 50CM
BC2.5M/W500S - ESTEIRA INOX LONA 2,5M X 50CM
BTT900 / BTT1000 - MESA ACUMULADORA GIRATÓRIA
ERC11M/D - ESTEIRA FLEXÍVEL C/ ROLETES MOTORIZADOS
ESTEIRA ARTICULADA RETA MODULAR
ESTEIRA MOTORIZADA CURVA 90 GRAUS
ESTEIRA TRANSPORTADORA 1M C/ CONTROLE DE VELOC.
PAGINADORA ROTATIVA EM AÇO INOX
RC1M - ESTEIRA DE ROLETES LIVRES 1 M
RC1M/D - ESTEIRA COM ROLETES MOTORIZADA
RC1M/DP - ESTEIRA DE ROLETES
RC1M/V90 - ESTEIRA C/ AJUSTE 90 GRAUS
RC2M - ESTEIRA TRANSPORTE DE CAIXA
RC2M/D - ESTEIRA TRANSPORTE DE CAIXA COM MOTOR
ZC7200 - ALIMENTADOR ELEVADOR DE PRODUTOS TIPO "Z"
Fechadoras e Seladoras de Caixa (15)
AS323 - SELADORA SUPERIOR DE ABAS
AS723 - SELADORA AUTOMÁTICA 4 LADOS
AS823A / AS823B - SELADORA PNEUMÁTICA SEMI-AUTOMÁTICA
FX-AT5050B - SELADORA AUTOMÁTICA
FX-AT5050D/HS - SELADORA SEMI-AUTOMÁTICA INOX
FX-AT5050 - SELADORA SEMI-AUTOMÁTICA
FXJ4030 - SELADORA SEMI-AUTOMÁTICA
FXJ5050 / FXJ5050S - SELADORA SEMI-AUTOMÁTICA
FXJ6050 / FXJ6050/EC - SELADORA SEMI-AUTOMÁTICA
FXJ6060 - SELADORA SEMI-AUTOMÁTICA
FXJ9050T - SELADORA SEMI-AUTOMÁTICA
SPG-6050 - SELADORA AUTOMÁTICA C/ FITA GOMADA
Misturadores e Tanques (7)
MOTION V-15 / V-100 / V-300 / V-500 / V-1000 - MIXER MODELO "V"
TANQUE 500 LITROS C/ MIXER E SISTEMA DE VÁCUO
TANQUE REATOR ABERTO ENCAMISADO 50L C/ MIXER
Moinhos Trituradores (2)
MC50 - MOINHO COLOIDAL
MC80 - MOINHO COLOIDAL
Montadoras de Caixas (6)
AS923B - FORMADORA DE FUNDO SEMIAUTOMÁTICA
CE16 - MONTADORA AUTOMÁTICA
CES4035N/A - MONTADORA C/ ALIM. PNEUMÁTICA
CES4530N - MONTADORA AUTOMÁTICA
CES5040V/A - MONTADORA AUTOMÁTICA
CONJUNTO CE16+AS323 - MONTADORA AUTOMÁTICA
Prensas e Polidoras de Comprimidos (12)
FS 5 P / FS 9 P / FS 10 P / FS 15 M - PRENSA AUTOMÁTICA ROTATIVA
FS 17M(F) - PRENSA ROTATIVA C/ ALIM. FORÇADA
FS 23 GE PRO - COMPRESSORA PARA COMPRIMIDOS EFERVESCENTES
FS T420-31D - PRENSA ROTATIVA P/ COMPRIMIDOS (NORMAL E DUPLA COR)
FS420-29G / FS550-39G - PRENSA ROTATIVA P/ ALTA COMPACTAÇÃO
UHTF30 - POLIDORA E DESEMPOEIRADORA
UHTF230 - POLIDORA E DESEMPOEIRADORA VERTICAL
Rosqueadoras (28)
ADC50 - ROSQUEADEIRA AUTOMÁTICA "BICO DE PATO"
ADC50/M / ADC50/MII - ROSQUEADEIRA AUTOM. DE BANCADA
ADC50/SII - ROSQUEADEIRA DE TAMPAS SEMI AUTOMÁTICA
ADC70 - ROSQUEADEIRA AUTOM. C/ ALIMENTAÇÃO DE TAMPAS
DHZ450A / DHZ450AII - ROSQUEADEIRA SEMI AUTOMÁTICA
DHZ450B / DHZ450BII - ROSQUEADEIRA SEMI AUTOMÁTICA
DHZ550B / DHZ550BII - ROSQUEADEIRA "BICO DE PATO" SEMI AUTOMÁTICA
DK-50D - ROSQUEADEIRA SEMI-AUTOM. P/ TAMPAS DE METAL
DK-50Z - ROSQUEADEIRA SEMI-AUTOM. P/ TAMPAS PLÁSTICAS
EC80 / EC90 - ROSQUEADEIRA ELÉTRICA MANUAL
PC90 - ROSQUEADEIRA PNEUMÁTICA MANUAL
XCG - ROSQUEADEIRA AUTOMÁTICA DE ALTA VELOCIDADE
XGG - ROSQUEADEIRA AUTOMÁTICA C/ ELEVADOR
XTB - ROSQUEADEIRA AUTOM. C/ SIST. INSERÇÃO SPOON/SCOOP
XTB/A - ROSQUEADEIRA AUTOMÁTICA C/ SIST. ALIM. AUTOMÁTICA
Rotuladoras (15)
ALB512 - ROTULADORA SEMI AUTOMÁTICA PARA LACRES
ARLM-160B / ARLM-200A / ARLM-200AII / ARLM-200B - ROTULADORA AUTOM. P/ FRASCOS CILÍNDRICOS
ARLM 220 - ROTULADORA AUTOMÁTICA PARA PRODUTOS PLANOS
MT50 / MT50/P - ROTULADORA ELÉTRICA MANUAL
MT150 - ROTULADORA SEMI AUTOMÁTICA PARA FRASCOS PLANOS
RBL80 / RBL80II - ROTULADora AUTOM. DE MESA LINEAR
RBL100 / RBL100II - ROTULADORA AUTOM. DE MESA
RBL120 - ROTULADORA DE BANCADA PARA PRODUTOS PLANOS
RL30 - ROTULADORA MANUAL P/ FRASCOS CILÍNDRICOS
Seladoras (83)
Bundling: BSF-6540XLT
Contínuas: FR750W/P, FRD1000 (diversos modelos), FRM-1120LD, FRP770W/400, HRS255, HRS640, PRATIC SEAL TC20, SCI770, SF150 (diversos modelos)
de Bandeja: HW-450, HW-550, SBV240TS, SBV320TS, SBV650A/3
de Pedal: FRP300, FRP400, FRP400T, FRP500, FRP600, FRP600T, FRP700, FRP800, FRP900, FRP1000, SP600L
em "L": ASS5640, BF650, BF850, BF850/25, BSF-5545LE, BSF-5640LG, BSF-5640LG-E, FQL450A, FQL450LB, FQL450LK, FQL450T
Manuais (de bancada): PCS100P, PCS200A, PCS200I, PCS200M, PCS200P, PCS300A, PCS300I, PCS300M, PCS400A, PCS500A
por Indução: DGYF500A, DGYF-S500C (Manuais); FL1500A, FL1500S, FL2000A, FL2000B, FL2000S, FL3000A, FL4000A (Automáticas)
a Vácuo: DZ(Q)400/2SB, DZ(Q)500/2SB, DZ260B, DZ280/2SE, DZ400/2SB, DZ500/2SB, DZ600/2SB, DZP600/2SB, DZP800/2SB, FRM-980ZQ/P, FRM-980ZQ/S, VM300TE/A, VM400E/B, VM400TE/B, VM500E/B, VM500TE/B, VM600E/B
Termoformadoras de Blister (6)
EVOLUTION 80 / 140 / 150 / 250 / 260 / 260H
Túneis de Encolhimento (20)
BS-20, BS-3020A, BS-4525A, BS-4535LA, BS-6535LA, BS-8030L
BSD1535P, BSD1535S, BSD1535ST, BSD350B, BSD400B, BSD4020A, BSD450B, BSD4525A
BS2450S- PLUS - TÚNEL PARA SLEEVE A VAPOR
HWS650 - TANQUE DE ENCOLHIMENTO POR IMERSÃO
`;

// 3. Comparison Logic
const lines = userListRaw.split('\n').map(l => l.trim()).filter(l => l.length > 0);
const missingItems: string[] = [];

// Helper to check if item exists using simple string matching
const existsInCatalog = (itemCode: string) => {
    const code = itemCode.toLowerCase().replace(/['"().]/g, '');
    const catalog = catalogContent.toLowerCase().replace(/['"().]/g, '');
    // console.log("Checking:", code, "Found:", catalog.includes(code));
    return catalog.includes(code);
};

for (const line of lines) {
    // Ignore headers (e.g. "Category (12)")
    if (line.match(/^[A-Za-z\s]+ \(\d+\)$/)) continue;
    if (!line.match(/[A-Za-z0-9]/)) continue; // ignore blank or punctuation

    // Parse logic
    let parts;
    if (line.includes(':')) {
        // e.g. "Bundling: BSF-6540XLT"
        parts = line.split(':');
        if (parts.length > 1) {
            const subItems = parts[1].split(',').map(s => s.trim());
            for (const subItem of subItems) {
                let cleanSub = subItem.split(' ')[0]; // E.g. "FRD1000" in "FRD1000 (diversos modelos)"
                if (cleanSub.length < 2) continue;
                if (!existsInCatalog(cleanSub)) {
                    missingItems.push(subItem + " (from line: " + line + ")");
                }
            }
            continue;
        }
    }

    parts = line.split(' - ');
    let modelCode = parts[0].trim();

    // Handle "XYZ / ABC"
    const subModels = modelCode.split('/').map(s => s.trim());
    let foundAny = false;

    for (const s of subModels) {
        if (existsInCatalog(s)) foundAny = true;
    }

    if (!foundAny) {
        // Check if the code is actually embedded in name (e.g. "ALIMENTADOR DE ROSCA")
        // Check if file contains "ALIMENTADOR DE ROSCA"
        if (existsInCatalog(modelCode)) foundAny = true;
    }

    if (!foundAny) {
        // console.log("Missing:", modelCode);
        missingItems.push(line);
    }
}

console.log("\n--- Missing Items Report ---");
console.log(missingItems.join('\n'));
